### ISSUE TITLE
[DEVOPS] Configurar pipeline CI/CD con GitHub Actions

### ISSUE THREAD

**Issue by echo-Nitram** [echo-Nitram/tuliga#3]
## 🎯 Descripción
Configurar pipeline completo de CI/CD con GitHub Actions para automatizar testing, build y deployment del proyecto TuLiga.

### 1. **CI Pipeline (Continuous Integration)**
- [ ] **Backend Testing**
  - [ ] Setup Python 3.11
  - [ ] Install dependencies
  - [ ] Run pytest with coverage
  - [ ] Lint with flake8/black
  - [ ] Type checking with mypy
- [ ] **Frontend Testing**  
  - [ ] Setup Node.js 18
  - [ ] Install dependencies
  - [ ] Run tests with Jest
  - [ ] Lint with ESLint
  - [ ] Type checking with TypeScript
- [ ] **Database Integration Tests**
  - [ ] Setup PostgreSQL service
  - [ ] Run migration tests
  - [ ] Seed test data

### 2. **CD Pipeline (Continuous Deployment)**
- [ ] **Build & Push Docker Images**
  - [ ] Build production images
  - [ ] Push to GitHub Container Registry
  - [ ] Tag with version/commit SHA
- [ ] **Deploy to Staging**
  - [ ] Auto-deploy on main branch
  - [ ] Run smoke tests
  - [ ] Notify team of deployment
- [ ] **Production Deployment**
  - [ ] Manual approval required
  - [ ] Blue-green deployment
  - [ ] Rollback capability

### `.github/workflows/ci.yml`
```yaml
name: CI
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # ... resto del workflow
```

### `.github/workflows/cd.yml`
```yaml
name: CD
on:
  workflow_run:
    workflows: [\"CI\"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # ... deployment logic
```

## 🔧 Herramientas y Servicios
- [ ] **GitHub Actions** - CI/CD runner
- [ ] **GitHub Container Registry** - Docker images
- [ ] **SonarCloud** - Code quality analysis
- [ ] **Codecov** - Coverage reporting
- [ ] **Dependabot** - Dependency updates
- [ ] **Railway/Render** - Staging environment
- [ ] **Slack/Discord** - Notifications

## 📊 Quality Gates
- [ ] **Code Coverage:** Mínimo 80%
- [ ] **Security Scan:** 0 vulnerabilidades críticas
- [ ] **Performance:** Build < 5 minutos
- [ ] **Tests:** 100% passing
- [ ] **Linting:** 0 errores críticos

## 🔒 Secrets a Configurar
- [ ] `DOCKER_USERNAME` & `DOCKER_PASSWORD`
- [ ] `DATABASE_URL` para testing
- [ ] `RAILWAY_TOKEN` para deployment
- [ ] `SLACK_WEBHOOK` para notificaciones
- [ ] `SONAR_TOKEN` para análisis de código

## 📈 Métricas y Monitoring
- [ ] **Build Success Rate** - Target: >95%
- [ ] **Deployment Frequency** - Daily deployments
- [ ] **Lead Time** - < 1 hora desde commit
- [ ] **Mean Time to Recovery** - < 2 horas
- [ ] **Change Failure Rate** - < 5%

## ✅ Criterios de Aceptación
- [ ] CI pipeline ejecuta en < 10 minutos
- [ ] Tests automatizados cubren backend y frontend
- [ ] Deploy automático a staging en cada merge a main
- [ ] Production deploy requiere aprobación manual
- [ ] Rollback funciona correctamente
- [ ] Notificaciones configuradas para el equipo
- [ ] Documentación de workflows actualizada

## 🚀 Prioridad
**Media** - Infraestructura fundamental para escalabilidad

## 📅 Timeline
**Estimado:** 3-4 días

## 📚 Referencias
- [GitHub Actions Documentation](https://docs.github.com/en/actions)
- [FastAPI + PostgreSQL CI](https://github.com/tiangolo/fastapi/blob/master/.github/workflows/test.yml)
- [Next.js CI/CD Best Practices](https://nextjs.org/docs/deployment)
